
model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointMetaBaseEncoder_X3D
    blocks: [1, 4, 7, 4, 4] 
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1
    sa_use_res: False 
    width: 64 
    in_channels: 4
    expansion: 1 #4
    radius: 0.1
    nsample: 32 
    x3d_layers: [False,False,False,True,True]
    NCP: 'true'
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
      es_type: 'pca'
      structure_kernel_args:
          hidden_dim: 32
          denoise: 'true'
          modu: 'true'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: PointNextDecoder
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: null
    norm_args:
      norm: 'bn'

batch_size: 8
seed: 1111 #4333 #4333 #2425